language: java
services:
  - docker

sudo: required

jdk:
  - openjdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean assemble

after_script:
  - docker build -t adarshr/hello-world .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push adarshr/hello/world

install: true